<a href="https://colab.research.google.com/github/shreya2118/Deep_learning/blob/main/backpropagation_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CODE USING FOR LOOPS AND BY SCRATCH**

In [43]:
import numpy as np
import pandas as pd

In [44]:
df=pd.DataFrame(([8,8,4],[7,9,5],[6,10,6],[5,12,7]),columns=['cgpa','score','lpa'])

In [45]:
df

cgpa  score  lpa
0     8      8    4
1     7      9    5
2     6     10    6
3     5     12    7

Step 1: initialize parameters==, with this function: we will give them the dimension of number of neurons in input layer, hidden layer and output layer and then it will automatically generates the number of learning parametrs found.


In [46]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters={}
  L=len(layer_dims)
  for i in range(1,L):
    parameters['W'+str(i)]=np.ones((layer_dims[i-1],layer_dims[i]))*0.1
    parameters['b'+str(i)]=np.zeros((layer_dims[i],1))
  return parameters


Now, the "linear_forward" function calculates the output of every neuron present in the structure

In [47]:
def linear_forward(A_prev,W,b):
  Z=np.dot(W.T,A_prev)+ b

  return Z

the main function which will perform the forward propagation

In [48]:
def L_layer_forward(X,parameters):
  A=X
  L=len(parameters)//2                #number of layers in neural network
  for i in range(1,L+1):
    A_prev=A
    W1=parameters['W'+str(i)]
    b1=parameters['b'+str(i)]

    #print("A"+str(i-1)+': ',A_prev)
    #print("W"+str(i)+': ',W1)
    #print("b"+str(i)+': ',b1)
    #print("--"*20)

    A=linear_forward(A_prev,W1,b1)
    #print("A"+str(i)+': ',A)
    #print("**"*20)
  return A,A_prev


this is the step where we are predicting the output of every student

In [49]:

X=df[['cgpa','score']].values[0].reshape(2,1)
y=df[['lpa']].values[0][0]

#if we print "X" it will give the two inputs of first student
#and if we print"y" it will give us the value of lpa(input)

#paramter initialization:
parameters=initialize_parameters([2,2,1])
L_layer_forward(X, parameters)

(array([[0.32]]),
 array([[1.6],
        [1.6]]))

update paramters using gradient descent: these are all 9 formulaes of the derivatives we calculated

In [50]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [51]:
X=df[['cgpa','score']].values[0].reshape(2,1)
y=df[['lpa']].values[0][0]

#paramter initialization:
parameters=initialize_parameters([2,2,1])
y_hat,A1=L_layer_forward(X, parameters)
y_hat=y_hat[0][0]                                          # for 1st student

update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [52]:
X=df[['cgpa','score']].values[1].reshape(2,1)
y=df[['lpa']].values[1][0]

y_hat,A1=L_layer_forward(X, parameters)
y_hat=y_hat[0][0]                                          # for 2nd student

update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]),
 'b1': array([[0.0019667],
        [0.0019667]]),
 'W2': array([[0.12712927],
        [0.12712927]]),
 'b2': array([[0.13612818]])}

In [53]:
X=df[['cgpa','score']].values[2].reshape(2,1)
y=df[['lpa']].values[2][0]

y_hat,A1=L_layer_forward(X, parameters)
y_hat=y_hat[0][0]                                          # for 3rd student

update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.12409711, 0.13272353],
        [0.12412266, 0.13276611]]),
 'b1': array([[0.00355129],
        [0.00355555]]),
 'W2': array([[0.14692424],
        [0.14731907]]),
 'b2': array([[0.15810417]])}

In [54]:
X=df[['cgpa','score']].values[3].reshape(2,1)
y=df[['lpa']].values[3][0]

#paramter initialization:
parameters=initialize_parameters([2,2,1])
y_hat,A1=L_layer_forward(X, parameters)
y_hat=y_hat[0][0]                                          # for 4th student

update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.10816809, 0.11960342],
        [0.10816809, 0.11960342]]),
 'b1': array([[0.00163362],
        [0.00163362]]),
 'W2': array([[0.122644],
        [0.122644]]),
 'b2': array([[0.135964]])}

now, we write the for loop for the number of epochs to run

In [57]:
#epochs implementation
parameters=initialize_parameters([2,2,1])

epochs=5
for i in range(epochs):
  loss=[]
  for j in range(df.shape[0]):
    X=df[['cgpa','score']].values[j].reshape(2,1)
    y=df[['lpa']].values[j][0]

    y_hat,A1=L_layer_forward(X, parameters)
    y_hat=y_hat[0][0]                                          # for j th student

    update_parameters(parameters,y,y_hat,A1,X)
    loss.append((y-y_hat)**2)
  print("Epoch- ",i+1,"Loss- ",np.array(loss).mean())

parameters

Epoch-  1 Loss-  25.321744156025517
Epoch-  2 Loss-  18.320004165722047
Epoch-  3 Loss-  9.473661050729628
Epoch-  4 Loss-  3.2520938634031613
Epoch-  5 Loss-  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

**CODE USING KERAS, TENSORFLOW**

In [58]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [59]:
model=Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [60]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

random initialization of weights

In [61]:
model.get_weights()

[array([[ 0.6562332,  0.5001923],
        [-0.9121481, -1.0733098]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.3488579 ],
        [ 0.10584319]], dtype=float32),
 array([0.], dtype=float32)]

In [62]:
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
             np.array([0.,0.],dtype=np.float32),
             np.array([[0.1],
                       [0.1]],dtype=np.float32),
             np.array([0.],dtype=np.float32)]

In [63]:
model.set_weights(new_weights)

In [64]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [65]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [67]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,batch_size=1,verbose=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.8375
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 29.5913
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25.0644
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 31.0453
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 27.6757
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 29.6143
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 23.4094
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24.1108
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26.4798
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 22.1223 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 23.5073
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 21.1925
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 18.9658
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.5164
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 22.9319
Epoch 16/75
4/4 ━━

In [68]:
model.get_weights()

[array([[0.37867838, 0.37867838],
        [0.37301406, 0.37301406]], dtype=float32),
 array([0.27880713, 0.27880713], dtype=float32),
 array([[0.37956998],
        [0.37956998]], dtype=float32),
 array([0.20843455], dtype=float32)]